/* ============================================================
   SEMPER FIDELIS — content & translations (pl / en / ru / de / fr)
   ============================================================ */
const I18N = {

  /* ==================== POLSKI ==================== */
  pl: {
    ui: {
      nav_home: "Start", nav_prayers: "Modlitwy", nav_songs: "Pieśni",
      nav_knowledge: "Wiedza", nav_facts: "Ciekawostki", nav_candles: "Kaplica",
      hero_kicker: "Przewodnik Chrześcijanina",
      hero_title: "Zawsze wierni — w modlitwie, pieśni i codziennym życiu",
      hero_sub: "Miejsce ciszy i światła. Zbiór modlitw, pieśni i wiedzy o wierze — w pięciu językach, dla każdego, kto szuka Boga.",
      hero_cta1: "Otwórz modlitewnik", hero_cta2: "Zapal świecę 🕯",
      verse_label: "Werset dnia",
      prayers_title: "Modlitwy",
      prayers_sub: "Słowa, które od wieków niosą ludzi ku niebu. Kliknij, aby otworzyć modlitwę.",
      songs_title: "Pieśni",
      songs_sub: "Kto śpiewa, ten dwa razy się modli — św. Augustyn.",
      knowledge_title: "Wiedza o wierze",
      knowledge_sub: "Rok liturgiczny, sakramenty i aniołowie — poznaj bogactwo tradycji chrześcijańskiej.",
      facts_title: "Ciekawostki",
      facts_sub: "Zaskakujące fakty z dwóch tysięcy lat historii chrześcijaństwa.",
      candles_title: "Kaplica światła",
      candles_sub: "Zapal wirtualną świecę w swojej intencji. Niech płomień przypomina o Twojej modlitwie.",
      candles_placeholder: "Twoja intencja (np. za rodzinę)...",
      candles_btn: "Zapal świecę",
      candles_note: "Świece pozostają zapalone na tym urządzeniu przez 7 dni.",
      candles_empty: "Bądź pierwszą osobą, która zapali dziś świecę...",
      tts_listen: "Odsłuchaj",
      tts_stop: "Zatrzymaj",
      ed_mode: "Tryb edycji treści",
      ed_edit: "Edytuj",
      ed_add_prayer: "Dodaj modlitwę",
      ed_add_song: "Dodaj pieśń",
      ed_add_fact: "Dodaj ciekawostkę",
      ed_add_card: "Dodaj kartę",
      ed_icon: "Ikona (emoji)",
      ed_name: "Tytuł",
      ed_text: "Treść",
      ed_meta: "Podpis (np. autor, rok)",
      ed_lyrics: "Tekst pieśni",
      ed_save: "Zapisz",
      ed_cancel: "Anuluj",
      ed_delete: "Usuń",
      ed_revert: "Przywróć oryginał",
      ed_export: "Eksportuj",
      ed_import: "Importuj",
      ed_done: "Zakończ edycję",
      ed_hint: "Kliknij flagę, aby dodać tłumaczenie w innym języku. Gdy tłumaczenia brakuje, wyświetlana jest wersja w innym dostępnym języku.",
      ed_need_content: "Uzupełnij treść w co najmniej jednym języku.",
      ed_import_ok: "Twoje treści zostały zaimportowane.",
      ed_import_err: "Nie udało się odczytać pliku.",
      ed_export_ok: "Plik z twoimi treściami został pobrany.",
      ed_confirm_delete: "Usunąć ten element?",
      footer_verse: "„Ja jestem światłością świata. Kto idzie za Mną, nie będzie chodził w ciemności.” — J 8,12",
      footer_note: "Stworzone z wiarą i nadzieją · Soli Deo Gloria",
    },
    verses: [
      { t: "Pan jest moim pasterzem, nie brak mi niczego.", r: "Psalm 23,1" },
      { t: "Wszystko mogę w Tym, który mnie umacnia.", r: "Flp 4,13" },
      { t: "Nie bój się, bo Ja jestem z tobą.", r: "Iz 41,10" },
      { t: "Miłość cierpliwa jest, łaskawa jest.", r: "1 Kor 13,4" },
      { t: "Przyjdźcie do Mnie wszyscy, którzy utrudzeni jesteście, a Ja was pokrzepię.", r: "Mt 11,28" },
      { t: "Bądźcie mocni w Panu — siłą Jego potęgi.", r: "Ef 6,10" },
      { t: "Serce czyste stwórz we mnie, Boże.", r: "Psalm 51,12" },
    ],
    prayers: [
      { icon: "✝", name: "Ojcze nasz", text: "Ojcze nasz, któryś jest w niebie,\nświęć się imię Twoje;\nprzyjdź królestwo Twoje;\nbądź wola Twoja jako w niebie, tak i na ziemi.\nChleba naszego powszedniego daj nam dzisiaj;\ni odpuść nam nasze winy, jako i my odpuszczamy naszym winowajcom;\ni nie wódź nas na pokuszenie,\nale nas zbaw ode złego.\nAmen." },
      { icon: "🌹", name: "Zdrowaś Maryjo", text: "Zdrowaś Maryjo, łaski pełna, Pan z Tobą,\nbłogosławionaś Ty między niewiastami\ni błogosławiony owoc żywota Twojego, Jezus.\nŚwięta Maryjo, Matko Boża,\nmódl się za nami grzesznymi\nteraz i w godzinę śmierci naszej.\nAmen." },
      { icon: "✨", name: "Chwała Ojcu", text: "Chwała Ojcu i Synowi, i Duchowi Świętemu,\njak była na początku, teraz i zawsze,\ni na wieki wieków.\nAmen." },
      { icon: "👼", name: "Aniele Boży", text: "Aniele Boży, stróżu mój,\nTy zawsze przy mnie stój.\nRano, wieczór, we dnie, w nocy\nbądź mi zawsze ku pomocy.\nStrzeż duszy, ciała mego\ni zaprowadź mnie do żywota wiecznego.\nAmen." },
      { icon: "🛡", name: "Modlitwa do św. Michała Archanioła", text: "Święty Michale Archaniele, wspomagaj nas w walce,\na przeciw niegodziwości i zasadzkom złego ducha bądź naszą obroną.\nOby go Bóg pogromić raczył, pokornie o to prosimy,\na Ty, Wodzu niebieskich zastępów,\nszatana i inne duchy złe, które na zgubę dusz ludzkich po tym świecie krążą,\nmocą Bożą strąć do piekła.\nAmen." },
      { icon: "📜", name: "Wyznanie wiary (Skład Apostolski)", text: "Wierzę w Boga, Ojca wszechmogącego, Stworzyciela nieba i ziemi.\nI w Jezusa Chrystusa, Syna Jego jedynego, Pana naszego,\nktóry się począł z Ducha Świętego, narodził się z Maryi Panny,\numęczon pod Ponckim Piłatem, ukrzyżowan, umarł i pogrzebion,\nzstąpił do piekieł, trzeciego dnia zmartwychwstał,\nwstąpił na niebiosa, siedzi po prawicy Boga Ojca wszechmogącego,\nstamtąd przyjdzie sądzić żywych i umarłych.\nWierzę w Ducha Świętego, święty Kościół powszechny,\nświętych obcowanie, grzechów odpuszczenie,\nciała zmartwychwstanie, żywot wieczny.\nAmen." },
      { icon: "📿", name: "Różaniec", text: "Czym jest ta modlitwa?\nRóżaniec to medytacyjna modlitwa, w której — powtarzając „Zdrowaś Maryjo” — rozważamy razem z Maryją najważniejsze wydarzenia z życia Jezusa, zwane tajemnicami. Według tradycji przekazała go św. Dominikowi sama Matka Boża (XIII wiek), a rozpowszechnili go dominikanie, zwłaszcza bł. Alan de la Roche. Wielkim orędownikiem różańca był papież Leon XIII, zwany „papieżem różańca”, a tajemnice światła dodał św. Jan Paweł II w 2002 roku.\n\nKiedy go odmawiać?\nW każdej chwili — najczęściej wieczorem, w rodzinie lub samotnie. Miesiącem różańca jest październik (wspomnienie Matki Bożej Różańcowej przypada 7 października), a każda część tajemnic ma swoje tradycyjne dni tygodnia.\n\nJak modlić się na paciorkach?\n[Na krzyżyku] Znak krzyża, następnie „Wierzę w Boga” (Skład Apostolski).\n[Na pierwszym dużym paciorku] „Ojcze nasz”.\n[Na trzech małych paciorkach] Trzy „Zdrowaś Maryjo” — o wiarę, nadzieję i miłość.\n[Przed medalikiem] „Chwała Ojcu”.\n[Zapowiedź tajemnicy] Wymień tajemnicę do rozważania, np. „Tajemnica pierwsza radosna — Zwiastowanie”.\n[Na dużym paciorku] „Ojcze nasz”.\n[Na dziesięciu małych paciorkach] Dziesięć „Zdrowaś Maryjo”, rozważając tajemnicę.\n[Po każdej dziesiątce] „Chwała Ojcu” i modlitwa fatimska: „O mój Jezu, przebacz nam nasze grzechy, zachowaj nas od ognia piekielnego, zaprowadź wszystkie dusze do nieba i dopomóż szczególnie tym, którzy najbardziej potrzebują Twojego miłosierdzia”.\nTak samo odmawia się kolejne cztery dziesiątki. [Na zakończenie] „Pod Twoją obronę” lub „Witaj, Królowo” i znak krzyża.\n\nTajemnice różańca:\n• Radosne (poniedziałek i sobota): Zwiastowanie, Nawiedzenie św. Elżbiety, Narodzenie Jezusa, Ofiarowanie w świątyni, Odnalezienie Jezusa w świątyni.\n• Światła (czwartek): Chrzest w Jordanie, Cud w Kanie Galilejskiej, Głoszenie królestwa Bożego, Przemienienie na górze Tabor, Ustanowienie Eucharystii.\n• Bolesne (wtorek i piątek): Modlitwa w Ogrójcu, Biczowanie, Cierniem ukoronowanie, Droga krzyżowa, Ukrzyżowanie.\n• Chwalebne (środa i niedziela): Zmartwychwstanie, Wniebowstąpienie, Zesłanie Ducha Świętego, Wniebowzięcie Maryi, Ukoronowanie Maryi na Królową nieba i ziemi." },
      { icon: "❤️", name: "Koronka do Bożego Miłosierdzia", text: "Czym jest ta modlitwa?\nKoronkę do Bożego Miłosierdzia podyktował sam Pan Jezus św. Faustynie Kowalskiej w Wilnie w 1935 roku, a jej treść zapisana jest w „Dzienniczku”. Na cały świat rozpowszechnili ją apostołowie Bożego Miłosierdzia, szczególnie św. Jan Paweł II, który kanonizował siostrę Faustynę w 2000 roku i ustanowił Niedzielę Miłosierdzia Bożego (pierwsza niedziela po Wielkanocy). Odmawia się ją na zwykłym różańcu i trwa zaledwie kilka minut.\n\nKiedy ją odmawiać?\nSzczególnie o godzinie 15:00 — w Godzinie Miłosierdzia, chwili śmierci Jezusa na krzyżu. Pan Jezus obiecał wielkie łaski tym, którzy ją odmawiają, zwłaszcza przy konających. Od Wielkiego Piątku do Niedzieli Miłosierdzia odprawia się nowennę z koronki.\n\nJak modlić się na paciorkach?\n[Na początku] Znak krzyża, następnie: „Ojcze nasz”, „Zdrowaś Maryjo” i „Wierzę w Boga”.\n[Na dużych paciorkach — przed każdą dziesiątką] „Ojcze Przedwieczny, ofiaruję Ci Ciało i Krew, Duszę i Bóstwo najmilszego Syna Twojego, a Pana naszego Jezusa Chrystusa, na przebłaganie za grzechy nasze i całego świata”.\n[Na małych paciorkach — 10 razy] „Dla Jego bolesnej męki miej miłosierdzie dla nas i całego świata”.\nTak samo odmawia się wszystkie pięć dziesiątek.\n[Na zakończenie — 3 razy] „Święty Boże, Święty Mocny, Święty Nieśmiertelny, zmiłuj się nad nami i nad całym światem”.\n[Można dodać] „O Krwi i Wodo, któraś wypłynęła z Najświętszego Serca Jezusowego jako zdrój miłosierdzia dla nas — ufam Tobie”." },
      { icon: "💙", name: "Pod Twoją obronę", text: "Pod Twoją obronę uciekamy się, Święta Boża Rodzicielko,\nnaszymi prośbami racz nie gardzić w potrzebach naszych,\nale od wszelakich złych przygód racz nas zawsze wybawiać,\nPanno chwalebna i błogosławiona.\nO Pani nasza, Orędowniczko nasza,\nPośredniczko nasza, Pocieszycielko nasza.\nZ Synem swoim nas pojednaj,\nSynowi swojemu nas polecaj,\nswojemu Synowi nas oddawaj.\nAmen." },
    ],
    songs: [
      { title: "Kiedy ranne wstają zorze", meta: "Pieśń poranna · F. Karpiński, XVIII w.", lyrics: "Kiedy ranne wstają zorze,\nTobie ziemia, Tobie morze,\nTobie śpiewa żywioł wszelki:\nBądź pochwalon, Boże wielki!\n\nA człowiek, który bez miary\nobsypany Twymi dary,\ncoś go stworzył i ocalił,\na czemuż by Cię nie chwalił?" },
      { title: "Święty Boże", meta: "Suplikacja · tradycyjna", lyrics: "Święty Boże, Święty mocny,\nŚwięty a Nieśmiertelny,\nzmiłuj się nad nami!\n\nOd powietrza, głodu, ognia i wojny\nwybaw nas, Panie!" },
      { title: "Serdeczna Matko", meta: "Pieśń maryjna · tradycyjna", lyrics: "Serdeczna Matko, Opiekunko ludzi,\nniech Cię płacz sierot do litości wzbudzi.\nWygnańcy Ewy do Ciebie wołamy:\nzlituj się, zlituj, niech się nie tułamy." },
    ],
    knowledge: [
      { tab: "Rok liturgiczny", intro: "Kościół przeżywa każdy rok jako wędrówkę przez życie Chrystusa — od oczekiwania, przez narodzenie i mękę, aż po zmartwychwstanie.", cards: [
        { icon: "🕯", title: "Adwent", text: "Cztery tygodnie radosnego oczekiwania na przyjście Zbawiciela. Czas wieńca adwentowego i rorat — Mszy ku czci Maryi o świcie." },
        { icon: "⭐", title: "Boże Narodzenie", text: "Świętowanie narodzin Jezusa w Betlejem. Okres trwa do święta Chrztu Pańskiego, a jego sercem jest Pasterka." },
        { icon: "✝", title: "Wielki Post", text: "Czterdzieści dni nawrócenia, modlitwy, postu i jałmużny — od Środy Popielcowej do Wielkiego Czwartku." },
        { icon: "🌅", title: "Wielkanoc", text: "Zmartwychwstanie Pańskie — najważniejsze święto chrześcijan. Radość paschalna trwa aż pięćdziesiąt dni, do Zesłania Ducha Świętego." },
        { icon: "🌿", title: "Okres zwykły", text: "Czas wzrastania w wierze dzień po dniu. Kolor zielony symbolizuje nadzieję i życie." },
      ]},
      { tab: "Sakramenty", intro: "Siedem sakramentów to widzialne znaki niewidzialnej łaski, towarzyszące człowiekowi od narodzin aż do końca ziemskiej drogi.", cards: [
        { icon: "💧", title: "Chrzest", text: "Brama do życia w Duchu — obmycie z grzechu pierworodnego i włączenie do wspólnoty Kościoła." },
        { icon: "🔥", title: "Bierzmowanie", text: "Umocnienie darami Ducha Świętego do dojrzałego i odważnego wyznawania wiary." },
        { icon: "🍞", title: "Eucharystia", text: "Źródło i szczyt życia chrześcijańskiego — realna obecność Chrystusa pod postaciami chleba i wina." },
        { icon: "🕊", title: "Pokuta", text: "Sakrament miłosierdzia — pojednanie z Bogiem i Kościołem przez wyznanie grzechów." },
        { icon: "🙌", title: "Namaszczenie chorych", text: "Umocnienie i pociecha dla cierpiących i chorych, znak bliskości Boga w słabości." },
        { icon: "💍", title: "Małżeństwo", text: "Przymierze mężczyzny i kobiety — obraz miłości Chrystusa do Kościoła." },
        { icon: "⛪", title: "Kapłaństwo", text: "Sakrament służby — posłanie do nauczania, uświęcania i prowadzenia ludu Bożego." },
      ]},
      { tab: "Aniołowie", intro: "„Aniołom swoim dał rozkaz o tobie, aby cię strzegli na wszystkich twych drogach” (Ps 91,11).", cards: [
        { icon: "👑", title: "Serafini i Cherubini", text: "Najbliżsi Bożego tronu. Serafini płoną miłością („Święty, Święty, Święty” — Iz 6), cherubini strzegą Bożej chwały." },
        { icon: "🛡", title: "Michał — „Któż jak Bóg?”", text: "Wódz zastępów niebieskich, pogromca zła, patron rycerzy i obrońca Kościoła." },
        { icon: "📯", title: "Gabriel — posłaniec", text: "Zwiastował Maryi narodzenie Jezusa. Jego imię znaczy „Bóg jest mocą”. Patron łączności i dyplomatów." },
        { icon: "🌿", title: "Rafał — uzdrowiciel", text: "„Bóg uzdrawia” — towarzysz Tobiasza w podróży, patron podróżnych, chorych i lekarzy." },
        { icon: "👼", title: "Anioł Stróż", text: "Według tradycji każdy człowiek ma swojego anioła, który go chroni i prowadzi. Ich święto obchodzimy 2 października." },
      ]},
    ],
    facts: [
      { icon: "📖", title: "Bestseller wszech czasów", text: "Biblia to najczęściej wydawana książka świata — przetłumaczona w całości lub częściowo na ponad 3600 języków." },
      { icon: "🐟", title: "Tajemny znak ryby", text: "Greckie słowo ICHTHYS (ryba) to akrostych: „Jezus Chrystus, Syn Boży, Zbawiciel”. Ryba była tajnym znakiem pierwszych chrześcijan." },
      { icon: "🙏", title: "Amen — niech się stanie", text: "Słowo „Amen” pochodzi z hebrajskiego i znaczy „zaprawdę, niech tak będzie”. Brzmi niemal identycznie w setkach języków świata." },
      { icon: "🕯", title: "Katakumby Rzymu", text: "Podziemne korytarze, w których modlili się i chowali zmarłych pierwsi chrześcijanie, ciągną się pod Rzymem na ponad 150 kilometrów." },
      { icon: "😭", title: "Najkrótszy werset", text: "Najkrótszy werset Biblii to „Jezus zapłakał” (J 11,35) — dwa słowa, które pokazują, jak bardzo Bóg jest blisko ludzkiego bólu." },
      { icon: "🎄", title: "Skąd choinka?", text: "Zwyczaj ubierania choinki narodził się w krajach niemieckich w XVI wieku — wiecznie zielone drzewko symbolizuje życie wieczne." },
      { icon: "⛪", title: "Najstarszy hymn", text: "„Phos Hilaron” (Pogodna Światłości) śpiewany jest nieprzerwanie od III wieku — to najstarszy hymn chrześcijański używany do dziś." },
      { icon: "🔔", title: "Anioł Pański trzy razy dziennie", text: "Dzwony kościelne biją tradycyjnie o 6:00, 12:00 i 18:00, wzywając do modlitwy „Anioł Pański” — zwyczaj sięga XIII wieku." },
    ],
  },

  /* ==================== ENGLISH ==================== */
  en: {
    ui: {
      nav_home: "Home", nav_prayers: "Prayers", nav_songs: "Hymns",
      nav_knowledge: "Faith", nav_facts: "Did you know?", nav_candles: "Chapel",
      hero_kicker: "A Christian's Companion",
      hero_title: "Ever faithful — in prayer, in song, in everyday life",
      hero_sub: "A place of stillness and light. A collection of prayers, hymns and knowledge of the faith — in five languages, for everyone who seeks God.",
      hero_cta1: "Open the prayer book", hero_cta2: "Light a candle 🕯",
      verse_label: "Verse of the day",
      prayers_title: "Prayers",
      prayers_sub: "Words that have carried people toward heaven for centuries. Click to open a prayer.",
      songs_title: "Hymns",
      songs_sub: "He who sings prays twice — St. Augustine.",
      knowledge_title: "Knowing the Faith",
      knowledge_sub: "The liturgical year, the sacraments and the angels — discover the richness of Christian tradition.",
      facts_title: "Did you know?",
      facts_sub: "Surprising facts from two thousand years of Christian history.",
      candles_title: "Chapel of Light",
      candles_sub: "Light a virtual candle for your intention. Let its flame remind you of your prayer.",
      candles_placeholder: "Your intention (e.g. for my family)...",
      candles_btn: "Light a candle",
      candles_note: "Candles stay lit on this device for 7 days.",
      candles_empty: "Be the first to light a candle today...",
      tts_listen: "Listen",
      tts_stop: "Stop",
      ed_mode: "Content editing mode",
      ed_edit: "Edit",
      ed_add_prayer: "Add a prayer",
      ed_add_song: "Add a hymn",
      ed_add_fact: "Add a fact",
      ed_add_card: "Add a card",
      ed_icon: "Icon (emoji)",
      ed_name: "Title",
      ed_text: "Text",
      ed_meta: "Caption (e.g. author, year)",
      ed_lyrics: "Lyrics",
      ed_save: "Save",
      ed_cancel: "Cancel",
      ed_delete: "Delete",
      ed_revert: "Restore original",
      ed_export: "Export",
      ed_import: "Import",
      ed_done: "Finish editing",
      ed_hint: "Click a flag to add a translation in another language. When a translation is missing, another available language version is shown.",
      ed_need_content: "Fill in the content in at least one language.",
      ed_import_ok: "Your content has been imported.",
      ed_import_err: "Could not read the file.",
      ed_export_ok: "A file with your content has been downloaded.",
      ed_confirm_delete: "Delete this item?",
      footer_verse: "“I am the light of the world. Whoever follows me will never walk in darkness.” — John 8:12",
      footer_note: "Made with faith and hope · Soli Deo Gloria",
    },
    verses: [
      { t: "The Lord is my shepherd; I shall not want.", r: "Psalm 23:1" },
      { t: "I can do all things through Christ who strengthens me.", r: "Philippians 4:13" },
      { t: "Fear not, for I am with you.", r: "Isaiah 41:10" },
      { t: "Love is patient, love is kind.", r: "1 Corinthians 13:4" },
      { t: "Come to me, all who labor and are heavy laden, and I will give you rest.", r: "Matthew 11:28" },
      { t: "Be strong in the Lord and in the strength of His might.", r: "Ephesians 6:10" },
      { t: "Create in me a clean heart, O God.", r: "Psalm 51:10" },
    ],
    prayers: [
      { icon: "✝", name: "Our Father", text: "Our Father, who art in heaven,\nhallowed be Thy name;\nThy kingdom come;\nThy will be done on earth as it is in heaven.\nGive us this day our daily bread;\nand forgive us our trespasses,\nas we forgive those who trespass against us;\nand lead us not into temptation,\nbut deliver us from evil.\nAmen." },
      { icon: "🌹", name: "Hail Mary", text: "Hail Mary, full of grace, the Lord is with thee;\nblessed art thou among women,\nand blessed is the fruit of thy womb, Jesus.\nHoly Mary, Mother of God,\npray for us sinners,\nnow and at the hour of our death.\nAmen." },
      { icon: "✨", name: "Glory Be", text: "Glory be to the Father, and to the Son, and to the Holy Spirit,\nas it was in the beginning, is now, and ever shall be,\nworld without end.\nAmen." },
      { icon: "👼", name: "Angel of God", text: "Angel of God, my guardian dear,\nto whom God's love commits me here,\never this day be at my side,\nto light and guard, to rule and guide.\nAmen." },
      { icon: "🛡", name: "Prayer to St. Michael", text: "Saint Michael the Archangel, defend us in battle;\nbe our protection against the wickedness and snares of the devil.\nMay God rebuke him, we humbly pray;\nand do thou, O Prince of the heavenly host,\nby the power of God, cast into hell Satan\nand all the evil spirits who prowl about the world seeking the ruin of souls.\nAmen." },
      { icon: "📜", name: "Profession of Faith (Apostles' Creed)", text: "I believe in God, the Father almighty, Creator of heaven and earth,\nand in Jesus Christ, His only Son, our Lord,\nwho was conceived by the Holy Spirit, born of the Virgin Mary,\nsuffered under Pontius Pilate, was crucified, died and was buried;\nHe descended into hell; on the third day He rose again from the dead;\nHe ascended into heaven, and is seated at the right hand of God the Father almighty;\nfrom there He will come to judge the living and the dead.\nI believe in the Holy Spirit, the holy catholic Church,\nthe communion of saints, the forgiveness of sins,\nthe resurrection of the body, and life everlasting.\nAmen." },
      { icon: "📿", name: "The Rosary", text: "What is this prayer?\nThe Rosary is a meditative prayer in which, while repeating the “Hail Mary”, we contemplate with Mary the most important events of the life of Jesus, called mysteries. According to tradition, Our Lady herself entrusted it to St. Dominic (13th century); it was spread by the Dominicans, especially Blessed Alan de la Roche. Pope Leo XIII, known as “the Pope of the Rosary”, was one of its greatest promoters, and the Luminous Mysteries were added by St. John Paul II in 2002.\n\nWhen to pray it?\nAt any time — most often in the evening, with the family or alone. October is the month of the Rosary (the feast of Our Lady of the Rosary falls on 7 October), and each set of mysteries has its traditional days of the week.\n\nHow to pray on the beads?\n[On the crucifix] Make the Sign of the Cross, then say the Apostles' Creed.\n[On the first large bead] “Our Father”.\n[On the three small beads] Three “Hail Marys” — for faith, hope and love.\n[Before the medal] “Glory Be”.\n[Announce the mystery] Name the mystery to be contemplated, e.g. “The first Joyful Mystery — the Annunciation”.\n[On the large bead] “Our Father”.\n[On the ten small beads] Ten “Hail Marys” while meditating on the mystery.\n[After each decade] “Glory Be” and the Fatima Prayer: “O my Jesus, forgive us our sins, save us from the fires of hell, lead all souls to heaven, especially those in most need of Thy mercy.”\nThe remaining four decades are prayed in the same way. [At the end] “Hail, Holy Queen” and the Sign of the Cross.\n\nThe Mysteries of the Rosary:\n• Joyful (Monday and Saturday): the Annunciation, the Visitation, the Nativity, the Presentation in the Temple, the Finding of Jesus in the Temple.\n• Luminous (Thursday): the Baptism in the Jordan, the Wedding at Cana, the Proclamation of the Kingdom of God, the Transfiguration, the Institution of the Eucharist.\n• Sorrowful (Tuesday and Friday): the Agony in the Garden, the Scourging at the Pillar, the Crowning with Thorns, the Carrying of the Cross, the Crucifixion.\n• Glorious (Wednesday and Sunday): the Resurrection, the Ascension, the Descent of the Holy Spirit, the Assumption of Mary, the Coronation of Mary as Queen of Heaven and Earth." },
      { icon: "❤️", name: "The Divine Mercy Chaplet", text: "What is this prayer?\nThe Chaplet of Divine Mercy was dictated by the Lord Jesus Himself to St. Faustina Kowalska in Vilnius in 1935, and its words are recorded in her “Diary”. It was spread throughout the world by the apostles of Divine Mercy, especially St. John Paul II, who canonized Sister Faustina in 2000 and established Divine Mercy Sunday (the first Sunday after Easter). It is prayed on ordinary rosary beads and takes only a few minutes.\n\nWhen to pray it?\nEspecially at 3 p.m. — the Hour of Mercy, the moment of Jesus' death on the cross. Jesus promised great graces to those who pray it, especially at the side of the dying. From Good Friday until Divine Mercy Sunday a novena of chaplets is prayed.\n\nHow to pray on the beads?\n[At the beginning] Make the Sign of the Cross, then say the “Our Father”, the “Hail Mary” and the Apostles' Creed.\n[On the large beads — before each decade] “Eternal Father, I offer You the Body and Blood, Soul and Divinity of Your dearly beloved Son, our Lord Jesus Christ, in atonement for our sins and those of the whole world.”\n[On the small beads — 10 times] “For the sake of His sorrowful Passion, have mercy on us and on the whole world.”\nAll five decades are prayed in the same way.\n[At the end — 3 times] “Holy God, Holy Mighty One, Holy Immortal One, have mercy on us and on the whole world.”\n[You may add] “O Blood and Water, which gushed forth from the Heart of Jesus as a fount of mercy for us — I trust in You.”" },
      { icon: "💙", name: "We Fly to Thy Protection (Sub Tuum Praesidium)", text: "We fly to thy protection,\nO holy Mother of God;\ndespise not our petitions in our necessities,\nbut deliver us always from all dangers,\nO glorious and blessed Virgin.\nAmen." },
    ],
    songs: [
      { title: "Amazing Grace", meta: "Hymn · John Newton, 1779", lyrics: "Amazing grace! How sweet the sound\nthat saved a wretch like me!\nI once was lost, but now am found;\nwas blind, but now I see.\n\n'Twas grace that taught my heart to fear,\nand grace my fears relieved;\nhow precious did that grace appear\nthe hour I first believed." },
      { title: "Holy, Holy, Holy", meta: "Hymn · Reginald Heber, 1826", lyrics: "Holy, holy, holy! Lord God Almighty!\nEarly in the morning our song shall rise to Thee;\nHoly, holy, holy, merciful and mighty!\nGod in three Persons, blessed Trinity!" },
      { title: "Be Thou My Vision", meta: "Ancient Irish hymn · 8th c.", lyrics: "Be Thou my vision, O Lord of my heart;\nnaught be all else to me, save that Thou art —\nThou my best thought, by day or by night,\nwaking or sleeping, Thy presence my light." },
    ],
    knowledge: [
      { tab: "Liturgical Year", intro: "The Church lives each year as a journey through the life of Christ — from expectation, through birth and passion, to resurrection.", cards: [
        { icon: "🕯", title: "Advent", text: "Four weeks of joyful expectation of the Saviour's coming. The season of the Advent wreath and dawn Masses in honour of Mary." },
        { icon: "⭐", title: "Christmas", text: "Celebrating the birth of Jesus in Bethlehem. The season lasts until the Baptism of the Lord, with Midnight Mass at its heart." },
        { icon: "✝", title: "Lent", text: "Forty days of conversion, prayer, fasting and almsgiving — from Ash Wednesday to Holy Thursday." },
        { icon: "🌅", title: "Easter", text: "The Resurrection of the Lord — the greatest Christian feast. Paschal joy lasts fifty days, until Pentecost." },
        { icon: "🌿", title: "Ordinary Time", text: "A time of growing in faith day by day. Its green colour symbolises hope and life." },
      ]},
      { tab: "Sacraments", intro: "The seven sacraments are visible signs of invisible grace, accompanying a person from birth to the end of the earthly journey.", cards: [
        { icon: "💧", title: "Baptism", text: "The gateway to life in the Spirit — washing away original sin and joining the community of the Church." },
        { icon: "🔥", title: "Confirmation", text: "Strengthening with the gifts of the Holy Spirit for a mature and courageous witness of faith." },
        { icon: "🍞", title: "Eucharist", text: "The source and summit of Christian life — the real presence of Christ under the forms of bread and wine." },
        { icon: "🕊", title: "Penance", text: "The sacrament of mercy — reconciliation with God and the Church through the confession of sins." },
        { icon: "🙌", title: "Anointing of the Sick", text: "Strength and comfort for the suffering and ill — a sign of God's closeness in weakness." },
        { icon: "💍", title: "Matrimony", text: "The covenant of a man and a woman — an image of Christ's love for the Church." },
        { icon: "⛪", title: "Holy Orders", text: "The sacrament of service — a mission to teach, sanctify and shepherd God's people." },
      ]},
      { tab: "Angels", intro: "“For He will command His angels concerning you, to guard you in all your ways” (Psalm 91:11).", cards: [
        { icon: "👑", title: "Seraphim & Cherubim", text: "Closest to God's throne. The seraphim burn with love (“Holy, Holy, Holy” — Isaiah 6); the cherubim guard God's glory." },
        { icon: "🛡", title: "Michael — “Who is like God?”", text: "Commander of the heavenly hosts, vanquisher of evil, patron of soldiers and defender of the Church." },
        { icon: "📯", title: "Gabriel — the Messenger", text: "He announced the birth of Jesus to Mary. His name means “God is my strength”. Patron of messengers and diplomats." },
        { icon: "🌿", title: "Raphael — the Healer", text: "“God heals” — Tobias's companion on his journey, patron of travellers, the sick and physicians." },
        { icon: "👼", title: "Guardian Angels", text: "Tradition holds that every person has an angel who protects and guides them. Their feast day is 2 October." },
      ]},
    ],
    facts: [
      { icon: "📖", title: "Bestseller of all time", text: "The Bible is the most published book in the world — translated in whole or in part into more than 3,600 languages." },
      { icon: "🐟", title: "The secret sign of the fish", text: "The Greek word ICHTHYS (fish) is an acrostic: “Jesus Christ, Son of God, Saviour”. The fish was a secret sign of the first Christians." },
      { icon: "🙏", title: "Amen — so be it", text: "The word “Amen” comes from Hebrew and means “truly, so be it”. It sounds almost identical in hundreds of languages." },
      { icon: "🕯", title: "The catacombs of Rome", text: "The underground corridors where the first Christians prayed and buried their dead stretch for over 150 kilometres beneath Rome." },
      { icon: "😭", title: "The shortest verse", text: "The shortest verse in the Bible is “Jesus wept” (John 11:35) — two words showing how close God is to human pain." },
      { icon: "🎄", title: "Where does the Christmas tree come from?", text: "The custom of decorating a tree arose in German lands in the 16th century — the evergreen symbolises eternal life." },
      { icon: "⛪", title: "The oldest hymn", text: "“Phos Hilaron” (O Gladsome Light) has been sung continuously since the 3rd century — the oldest Christian hymn still in use." },
      { icon: "🔔", title: "The Angelus three times a day", text: "Church bells traditionally ring at 6 am, noon and 6 pm, calling the faithful to the Angelus prayer — a custom dating back to the 13th century." },
    ],
  },

  /* ==================== РУССКИЙ ==================== */
  ru: {
    ui: {
      nav_home: "Главная", nav_prayers: "Молитвы", nav_songs: "Песнопения",
      nav_knowledge: "Вера", nav_facts: "Интересное", nav_candles: "Часовня",
      hero_kicker: "Спутник христианина",
      hero_title: "Всегда верны — в молитве, в песне, в повседневной жизни",
      hero_sub: "Место тишины и света. Собрание молитв, песнопений и знаний о вере — на пяти языках, для каждого, кто ищет Бога.",
      hero_cta1: "Открыть молитвослов", hero_cta2: "Зажечь свечу 🕯",
      verse_label: "Стих дня",
      prayers_title: "Молитвы",
      prayers_sub: "Слова, которые веками возносят людей к небу. Нажмите, чтобы открыть молитву.",
      songs_title: "Песнопения",
      songs_sub: "Кто поёт — молится дважды (св. Августин).",
      knowledge_title: "Знание веры",
      knowledge_sub: "Литургический год, таинства и ангелы — откройте богатство христианской традиции.",
      facts_title: "Интересные факты",
      facts_sub: "Удивительные факты из двух тысяч лет истории христианства.",
      candles_title: "Часовня света",
      candles_sub: "Зажгите виртуальную свечу о своём намерении. Пусть её пламя напоминает о вашей молитве.",
      candles_placeholder: "Ваше намерение (напр., о семье)...",
      candles_btn: "Зажечь свечу",
      candles_note: "Свечи горят на этом устройстве 7 дней.",
      candles_empty: "Станьте первым, кто зажжёт сегодня свечу...",
      tts_listen: "Прослушать",
      tts_stop: "Остановить",
      ed_mode: "Режим редактирования",
      ed_edit: "Редактировать",
      ed_add_prayer: "Добавить молитву",
      ed_add_song: "Добавить песнопение",
      ed_add_fact: "Добавить факт",
      ed_add_card: "Добавить карточку",
      ed_icon: "Иконка (эмодзи)",
      ed_name: "Заголовок",
      ed_text: "Текст",
      ed_meta: "Подпись (например, автор, год)",
      ed_lyrics: "Текст песнопения",
      ed_save: "Сохранить",
      ed_cancel: "Отмена",
      ed_delete: "Удалить",
      ed_revert: "Восстановить оригинал",
      ed_export: "Экспорт",
      ed_import: "Импорт",
      ed_done: "Завершить редактирование",
      ed_hint: "Нажмите на флаг, чтобы добавить перевод на другой язык. Если перевода нет, будет показана версия на другом доступном языке.",
      ed_need_content: "Заполните содержание хотя бы на одном языке.",
      ed_import_ok: "Ваши материалы импортированы.",
      ed_import_err: "Не удалось прочитать файл.",
      ed_export_ok: "Файл с вашими материалами загружен.",
      ed_confirm_delete: "Удалить этот элемент?",
      footer_verse: "«Я свет миру; кто последует за Мною, тот не будет ходить во тьме» — Ин 8:12",
      footer_note: "Создано с верой и надеждой · Soli Deo Gloria",
    },
    verses: [
      { t: "Господь — Пастырь мой; я ни в чём не буду нуждаться.", r: "Псалом 22:1" },
      { t: "Всё могу в укрепляющем меня Иисусе Христе.", r: "Флп 4:13" },
      { t: "Не бойся, ибо Я с тобою.", r: "Ис 41:10" },
      { t: "Любовь долготерпит, милосердствует.", r: "1 Кор 13:4" },
      { t: "Придите ко Мне, все труждающиеся и обременённые, и Я успокою вас.", r: "Мф 11:28" },
      { t: "Укрепляйтесь Господом и могуществом силы Его.", r: "Еф 6:10" },
      { t: "Сердце чистое сотвори во мне, Боже.", r: "Псалом 50:12" },
    ],
    prayers: [
      { icon: "✝", name: "Отче наш", text: "Отче наш, сущий на небесах!\nДа святится имя Твоё;\nда приидет Царствие Твоё;\nда будет воля Твоя и на земле, как на небе;\nхлеб наш насущный дай нам на сей день;\nи прости нам долги наши, как и мы прощаем должникам нашим;\nи не введи нас в искушение,\nно избавь нас от лукавого.\nАминь." },
      { icon: "🌹", name: "Радуйся, Мария", text: "Радуйся, Мария, благодати полная!\nГосподь с Тобою;\nблагословенна Ты между женами,\nи благословен плод чрева Твоего Иисус.\nСвятая Мария, Матерь Божия,\nмолись о нас, грешных,\nныне и в час смерти нашей.\nАминь." },
      { icon: "✨", name: "Слава Отцу", text: "Слава Отцу и Сыну и Святому Духу,\nи ныне, и присно,\nи во веки веков.\nАминь." },
      { icon: "👼", name: "Ангел Божий", text: "Ангел Божий, хранитель мой святой,\nвверенный мне благостью Небесной,\nв этот день будь рядом со мной:\nпросвещай, храни, направляй и веди меня.\nАминь." },
      { icon: "🛡", name: "Молитва святому Михаилу", text: "Святой Михаил Архангел, защити нас в битве;\nбудь нам защитой от козней и злобы диавола.\nДа запретит ему Бог, смиренно молим;\nа ты, Вождь воинства небесного,\nсилою Божией низвергни в ад сатану\nи прочих злых духов, бродящих по свету на погибель душ.\nАминь." },
      { icon: "📜", name: "Апостольский символ веры", text: "Верую в Бога, Отца Всемогущего, Творца неба и земли.\nИ в Иисуса Христа, единственного Его Сына, Господа нашего,\nкоторый был зачат от Духа Святого, родился от Марии Девы,\nстрадал при Понтии Пилате, был распят, умер и был погребён,\nсошёл в ад, в третий день воскрес из мёртвых,\nвосшёл на небеса и восседает одесную Бога Отца Всемогущего,\nоттуда придёт судить живых и мёртвых.\nВерую в Духа Святого, святую Вселенскую Церковь,\nобщение святых, прощение грехов,\nвоскресение тела, жизнь вечную.\nАминь." },
      { icon: "📿", name: "Розарий", text: "Что это за молитва?\nРозарий — это созерцательная молитва: повторяя «Радуйся, Мария», мы вместе с Марией размышляем о важнейших событиях жизни Иисуса, называемых тайнами. По преданию, сама Богородица вручила его святому Доминику (XIII век); распространяли его доминиканцы, особенно блаженный Алан де ла Рош. Великим покровителем Розария был папа Лев XIII — «папа Розария», а светлые тайны добавил святой Иоанн Павел II в 2002 году.\n\nКогда его читать?\nВ любое время — чаще всего вечером, в семье или в одиночестве. Октябрь — месяц Розария (память Пресвятой Девы Марии Розария — 7 октября), а у каждой части тайн есть свои традиционные дни недели.\n\nКак молиться по чёткам?\n[На распятии] Осени себя крестным знамением и прочитай «Верую» (Апостольский символ веры).\n[На первой большой бусине] «Отче наш».\n[На трёх малых бусинах] Три раза «Радуйся, Мария» — о вере, надежде и любви.\n[Перед медальоном] «Слава Отцу».\n[Объявление тайны] Назови тайну для размышления, например: «Первая радостная тайна — Благовещение».\n[На большой бусине] «Отче наш».\n[На десяти малых бусинах] Десять раз «Радуйся, Мария», размышляя о тайне.\n[После каждой десятки] «Слава Отцу» и Фатимская молитва: «О мой Иисус, прости нам наши грехи, избавь нас от адского огня, приведи все души на небо, особенно те, которые больше всего нуждаются в Твоём милосердии».\nОстальные четыре десятки читаются так же. [В завершение] «Под Твою защиту» или «Радуйся, Царица» и крестное знамение.\n\nТайны Розария:\n• Радостные (понедельник и суббота): Благовещение, Посещение Елизаветы, Рождество Иисуса, Сретение, Обретение Иисуса в храме.\n• Светлые (четверг): Крещение в Иордане, Чудо в Кане Галилейской, Провозглашение Царства Божия, Преображение, Установление Евхаристии.\n• Скорбные (вторник и пятница): Молитва в Гефсиманском саду, Бичевание, Увенчание терниями, Крестный путь, Распятие.\n• Славные (среда и воскресенье): Воскресение, Вознесение, Сошествие Святого Духа, Взятие Марии на небо, Увенчание Марии небесной славой." },
      { icon: "❤️", name: "Венчик Божьему Милосердию", text: "Что это за молитва?\nВенчик Божьему Милосердию продиктовал сам Господь Иисус святой Фаустине Ковальской в Вильнюсе в 1935 году; его слова записаны в её «Дневнике». По всему миру его распространили апостолы Божьего Милосердия, особенно святой Иоанн Павел II, который канонизировал сестру Фаустину в 2000 году и установил праздник Божьего Милосердия (первое воскресенье после Пасхи). Венчик читается на обычных чётках Розария и занимает всего несколько минут.\n\nКогда его читать?\nОсобенно в 15:00 — в Час Милосердия, час смерти Иисуса на кресте. Иисус обещал великие благодати тем, кто его читает, особенно рядом с умирающими. От Страстной пятницы до праздника Божьего Милосердия читается новенна из венчиков.\n\nКак молиться по чёткам?\n[В начале] Крестное знамение, затем: «Отче наш», «Радуйся, Мария» и «Верую».\n[На больших бусинах — перед каждой десяткой] «Отче Предвечный, приношу Тебе Тело и Кровь, Душу и Божество возлюбленного Сына Твоего, Господа нашего Иисуса Христа, во искупление грехов наших и всего мира».\n[На малых бусинах — 10 раз] «Ради Его скорбных страданий будь милосерден к нам и ко всему миру».\nТак же читаются все пять десяток.\n[В завершение — 3 раза] «Святый Боже, Святый Крепкий, Святый Бессмертный, помилуй нас и весь мир».\n[Можно добавить] «О Кровь и Вода, истёкшие из Сердца Иисуса как источник милосердия для нас — уповаю на Тебя»." },
      { icon: "💙", name: "Под Твою защиту", text: "Под Твою защиту прибегаем,\nСвятая Богородица!\nНе презри молений наших в скорбях наших,\nно от всех опасностей избавляй нас всегда,\nДева преславная и благословенная.\nВладычица наша, Защитница наша, Заступница наша!\nС Сыном Твоим примири нас,\nСыну Твоему поручай нас,\nк Сыну Твоему приводи всех нас.\nАминь." },
    ],
    songs: [
      { title: "Царю Небесный", meta: "Молитва-песнопение · древняя традиция", lyrics: "Царю Небесный, Утешителю,\nДуше истины,\nИже везде сый и вся исполняяй,\nСокровище благих и жизни Подателю,\nприиди и вселися в ны,\nи очисти ны от всякия скверны,\nи спаси, Блаже, души наша." },
      { title: "Свете тихий", meta: "Древний гимн · III век", lyrics: "Свете тихий святыя славы\nбезсмертнаго Отца Небеснаго,\nсвятаго, блаженнаго, Иисусе Христе!\nПришедше на запад солнца,\nвидевше свет вечерний,\nпоем Отца, Сына и Святаго Духа, Бога." },
      { title: "Тебе поем", meta: "Литургическое песнопение", lyrics: "Тебе поем,\nТебе благословим,\nТебе благодарим, Господи,\nи молим Ти ся, Боже наш." },
    ],
    knowledge: [
      { tab: "Литургический год", intro: "Церковь проживает каждый год как путь через жизнь Христа — от ожидания, через рождение и страдания, к воскресению.", cards: [
        { icon: "🕯", title: "Адвент / Рождественский пост", text: "Время радостного ожидания пришествия Спасителя, подготовки сердца молитвой и добрыми делами." },
        { icon: "⭐", title: "Рождество Христово", text: "Празднование рождения Иисуса в Вифлееме — одна из величайших радостей христианского года." },
        { icon: "✝", title: "Великий пост", text: "Сорок дней обращения, молитвы, поста и милостыни — путь к Пасхе." },
        { icon: "🌅", title: "Пасха", text: "Воскресение Господне — праздник праздников. Пасхальная радость длится пятьдесят дней, до Пятидесятницы." },
        { icon: "🌿", title: "Обычное время", text: "Время возрастания в вере день за днём. Зелёный цвет символизирует надежду и жизнь." },
      ]},
      { tab: "Таинства", intro: "Семь таинств — видимые знаки невидимой благодати, сопровождающие человека от рождения до конца земного пути.", cards: [
        { icon: "💧", title: "Крещение", text: "Врата жизни в Духе — омовение от первородного греха и вхождение в общину Церкви." },
        { icon: "🔥", title: "Миропомазание", text: "Укрепление дарами Святого Духа для зрелого и смелого исповедания веры." },
        { icon: "🍞", title: "Евхаристия", text: "Источник и вершина христианской жизни — реальное присутствие Христа под видами хлеба и вина." },
        { icon: "🕊", title: "Покаяние", text: "Таинство милосердия — примирение с Богом и Церковью через исповедание грехов." },
        { icon: "🙌", title: "Елеопомазание больных", text: "Укрепление и утешение для страдающих и больных — знак близости Бога в немощи." },
        { icon: "💍", title: "Брак", text: "Союз мужчины и женщины — образ любви Христа к Церкви." },
        { icon: "⛪", title: "Священство", text: "Таинство служения — послание учить, освящать и вести народ Божий." },
      ]},
      { tab: "Ангелы", intro: "«Ангелам Своим заповедает о тебе — охранять тебя на всех путях твоих» (Пс 90:11).", cards: [
        { icon: "👑", title: "Серафимы и херувимы", text: "Ближайшие к престолу Божию. Серафимы пламенеют любовью («Свят, Свят, Свят» — Ис 6), херувимы хранят славу Божию." },
        { icon: "🛡", title: "Михаил — «Кто как Бог?»", text: "Архистратиг небесных воинств, победитель зла, покровитель воинов и защитник Церкви." },
        { icon: "📯", title: "Гавриил — вестник", text: "Возвестил Марии рождение Иисуса. Его имя означает «сила Божия». Покровитель вестников и дипломатов." },
        { icon: "🌿", title: "Рафаил — целитель", text: "«Бог исцеляет» — спутник Товии в пути, покровитель путешественников, больных и врачей." },
        { icon: "👼", title: "Ангел-хранитель", text: "По преданию, у каждого человека есть ангел, который хранит и ведёт его по жизни." },
      ]},
    ],
    facts: [
      { icon: "📖", title: "Бестселлер всех времён", text: "Библия — самая издаваемая книга в мире, переведённая полностью или частично более чем на 3600 языков." },
      { icon: "🐟", title: "Тайный знак рыбы", text: "Греческое слово ИХТИС (рыба) — акростих: «Иисус Христос, Божий Сын, Спаситель». Рыба была тайным знаком первых христиан." },
      { icon: "🙏", title: "Аминь — да будет так", text: "Слово «Аминь» происходит из иврита и означает «истинно, да будет так». Оно звучит почти одинаково на сотнях языков мира." },
      { icon: "🕯", title: "Катакомбы Рима", text: "Подземные коридоры, где молились и хоронили усопших первые христиане, тянутся под Римом более чем на 150 километров." },
      { icon: "😭", title: "Самый короткий стих", text: "Самый короткий стих Библии — «Иисус прослезился» (Ин 11:35) — два слова о том, как близок Бог к человеческой боли." },
      { icon: "🎄", title: "Откуда рождественская ёлка?", text: "Обычай наряжать ёлку родился в немецких землях в XVI веке — вечнозелёное дерево символизирует вечную жизнь." },
      { icon: "⛪", title: "Древнейший гимн", text: "«Свете тихий» поётся непрерывно с III века — это древнейший христианский гимн, используемый до сих пор." },
      { icon: "🔔", title: "Колокола трижды в день", text: "Церковные колокола традиционно звонят утром, в полдень и вечером, призывая к молитве — обычай восходит к XIII веку." },
    ],
  },

  /* ==================== DEUTSCH ==================== */
  de: {
    ui: {
      nav_home: "Start", nav_prayers: "Gebete", nav_songs: "Lieder",
      nav_knowledge: "Glaube", nav_facts: "Wissenswertes", nav_candles: "Kapelle",
      hero_kicker: "Ein Begleiter für Christen",
      hero_title: "Immer treu — im Gebet, im Lied, im täglichen Leben",
      hero_sub: "Ein Ort der Stille und des Lichts. Eine Sammlung von Gebeten, Liedern und Glaubenswissen — in fünf Sprachen, für alle, die Gott suchen.",
      hero_cta1: "Gebetbuch öffnen", hero_cta2: "Kerze anzünden 🕯",
      verse_label: "Vers des Tages",
      prayers_title: "Gebete",
      prayers_sub: "Worte, die die Menschen seit Jahrhunderten zum Himmel tragen. Klicken Sie, um ein Gebet zu öffnen.",
      songs_title: "Kirchenlieder",
      songs_sub: "Wer singt, betet doppelt — hl. Augustinus.",
      knowledge_title: "Glaubenswissen",
      knowledge_sub: "Das Kirchenjahr, die Sakramente und die Engel — entdecken Sie den Reichtum der christlichen Tradition.",
      facts_title: "Wissenswertes",
      facts_sub: "Überraschende Fakten aus zweitausend Jahren christlicher Geschichte.",
      candles_title: "Kapelle des Lichts",
      candles_sub: "Zünden Sie eine virtuelle Kerze für Ihr Anliegen an. Möge ihre Flamme an Ihr Gebet erinnern.",
      candles_placeholder: "Ihr Anliegen (z. B. für die Familie)...",
      candles_btn: "Kerze anzünden",
      candles_note: "Kerzen bleiben auf diesem Gerät 7 Tage lang entzündet.",
      candles_empty: "Seien Sie heute die erste Person, die eine Kerze anzündet...",
      tts_listen: "Anhören",
      tts_stop: "Stopp",
      ed_mode: "Bearbeitungsmodus",
      ed_edit: "Bearbeiten",
      ed_add_prayer: "Gebet hinzufügen",
      ed_add_song: "Lied hinzufügen",
      ed_add_fact: "Fakt hinzufügen",
      ed_add_card: "Karte hinzufügen",
      ed_icon: "Symbol (Emoji)",
      ed_name: "Titel",
      ed_text: "Text",
      ed_meta: "Untertitel (z. B. Autor, Jahr)",
      ed_lyrics: "Liedtext",
      ed_save: "Speichern",
      ed_cancel: "Abbrechen",
      ed_delete: "Löschen",
      ed_revert: "Original wiederherstellen",
      ed_export: "Exportieren",
      ed_import: "Importieren",
      ed_done: "Bearbeitung beenden",
      ed_hint: "Klicken Sie auf eine Flagge, um eine Übersetzung in einer anderen Sprache hinzuzufügen. Fehlt eine Übersetzung, wird eine andere verfügbare Sprachversion angezeigt.",
      ed_need_content: "Füllen Sie den Inhalt in mindestens einer Sprache aus.",
      ed_import_ok: "Ihre Inhalte wurden importiert.",
      ed_import_err: "Die Datei konnte nicht gelesen werden.",
      ed_export_ok: "Eine Datei mit Ihren Inhalten wurde heruntergeladen.",
      ed_confirm_delete: "Dieses Element löschen?",
      footer_verse: "„Ich bin das Licht der Welt. Wer mir nachfolgt, wird nicht in der Finsternis umhergehen.“ — Joh 8,12",
      footer_note: "Mit Glaube und Hoffnung erstellt · Soli Deo Gloria",
    },
    verses: [
      { t: "Der Herr ist mein Hirte, mir wird nichts mangeln.", r: "Psalm 23,1" },
      { t: "Ich vermag alles durch den, der mich stark macht.", r: "Phil 4,13" },
      { t: "Fürchte dich nicht, denn ich bin mit dir.", r: "Jes 41,10" },
      { t: "Die Liebe ist langmütig, die Liebe ist gütig.", r: "1 Kor 13,4" },
      { t: "Kommt alle zu mir, die ihr mühselig und beladen seid; ich will euch erquicken.", r: "Mt 11,28" },
      { t: "Seid stark im Herrn und in der Macht seiner Stärke.", r: "Eph 6,10" },
      { t: "Erschaffe mir, Gott, ein reines Herz.", r: "Psalm 51,12" },
    ],
    prayers: [
      { icon: "✝", name: "Vater unser", text: "Vater unser im Himmel,\ngeheiligt werde dein Name.\nDein Reich komme.\nDein Wille geschehe, wie im Himmel, so auf Erden.\nUnser tägliches Brot gib uns heute.\nUnd vergib uns unsere Schuld,\nwie auch wir vergeben unsern Schuldigern.\nUnd führe uns nicht in Versuchung,\nsondern erlöse uns von dem Bösen.\nAmen." },
      { icon: "🌹", name: "Gegrüßet seist du, Maria", text: "Gegrüßet seist du, Maria, voll der Gnade,\nder Herr ist mit dir.\nDu bist gebenedeit unter den Frauen,\nund gebenedeit ist die Frucht deines Leibes, Jesus.\nHeilige Maria, Mutter Gottes,\nbitte für uns Sünder\njetzt und in der Stunde unseres Todes.\nAmen." },
      { icon: "✨", name: "Ehre sei dem Vater", text: "Ehre sei dem Vater und dem Sohn und dem Heiligen Geist,\nwie im Anfang, so auch jetzt und alle Zeit\nund in Ewigkeit.\nAmen." },
      { icon: "👼", name: "Schutzengelgebet", text: "Heiliger Schutzengel mein,\nlass mich dir empfohlen sein.\nIn allen Nöten steh mir bei\nund halte mich von Sünden frei.\nAn diesem Tag, ich bitte dich:\nbeschütze und bewahre mich.\nAmen." },
      { icon: "🛡", name: "Gebet zum hl. Michael", text: "Heiliger Erzengel Michael, verteidige uns im Kampfe;\ngegen die Bosheit und die Nachstellungen des Teufels sei unser Schutz.\nGott gebiete ihm, so bitten wir flehentlich;\ndu aber, Fürst der himmlischen Heerscharen,\nstoße den Satan und die anderen bösen Geister,\ndie in der Welt umhergehen, um die Seelen zu verderben,\ndurch die Kraft Gottes in die Hölle.\nAmen." },
      { icon: "📜", name: "Apostolisches Glaubensbekenntnis", text: "Ich glaube an Gott, den Vater, den Allmächtigen,\nden Schöpfer des Himmels und der Erde,\nund an Jesus Christus, seinen eingeborenen Sohn, unsern Herrn,\nempfangen durch den Heiligen Geist, geboren von der Jungfrau Maria,\ngelitten unter Pontius Pilatus, gekreuzigt, gestorben und begraben,\nhinabgestiegen in das Reich des Todes,\nam dritten Tage auferstanden von den Toten,\naufgefahren in den Himmel;\ner sitzt zur Rechten Gottes, des allmächtigen Vaters;\nvon dort wird er kommen, zu richten die Lebenden und die Toten.\nIch glaube an den Heiligen Geist, die heilige katholische Kirche,\nGemeinschaft der Heiligen, Vergebung der Sünden,\nAuferstehung der Toten und das ewige Leben.\nAmen." },
      { icon: "📿", name: "Der Rosenkranz", text: "Was ist das für ein Gebet?\nDer Rosenkranz ist ein betrachtendes Gebet: Während wir das „Gegrüßet seist du, Maria“ wiederholen, betrachten wir mit Maria die wichtigsten Ereignisse aus dem Leben Jesu, die Geheimnisse genannt werden. Der Überlieferung nach übergab die Gottesmutter selbst den Rosenkranz dem heiligen Dominikus (13. Jahrhundert); verbreitet wurde er durch die Dominikaner, besonders durch den seligen Alanus de Rupe. Ein großer Förderer war Papst Leo XIII., der „Rosenkranzpapst“; die lichtreichen Geheimnisse fügte der heilige Johannes Paul II. im Jahr 2002 hinzu.\n\nWann betet man ihn?\nZu jeder Zeit — meist am Abend, in der Familie oder allein. Der Oktober ist der Rosenkranzmonat (das Fest Unserer Lieben Frau vom Rosenkranz ist am 7. Oktober), und jede Gruppe von Geheimnissen hat ihre traditionellen Wochentage.\n\nWie betet man an den Perlen?\n[Am Kreuz] Kreuzzeichen, dann das Apostolische Glaubensbekenntnis.\n[An der ersten großen Perle] „Vater unser“.\n[An den drei kleinen Perlen] Dreimal „Gegrüßet seist du, Maria“ — um Glaube, Hoffnung und Liebe.\n[Vor dem Medaillon] „Ehre sei dem Vater“.\n[Ansage des Geheimnisses] Nenne das Geheimnis, das betrachtet wird, z. B. „Das erste freudenreiche Geheimnis — die Verkündigung“.\n[An der großen Perle] „Vater unser“.\n[An den zehn kleinen Perlen] Zehnmal „Gegrüßet seist du, Maria“, während man das Geheimnis betrachtet.\n[Nach jedem Gesätz] „Ehre sei dem Vater“ und das Fatima-Gebet: „O mein Jesus, verzeih uns unsere Sünden, bewahre uns vor dem Feuer der Hölle, führe alle Seelen in den Himmel, besonders jene, die deiner Barmherzigkeit am meisten bedürfen.“\nDie übrigen vier Gesätze betet man ebenso. [Zum Abschluss] „Salve Regina“ (Sei gegrüßt, o Königin) und das Kreuzzeichen.\n\nDie Geheimnisse des Rosenkranzes:\n• Freudenreich (Montag und Samstag): die Verkündigung, der Besuch bei Elisabet, die Geburt Jesu, die Darstellung im Tempel, die Wiederauffindung Jesu im Tempel.\n• Lichtreich (Donnerstag): die Taufe im Jordan, die Hochzeit zu Kana, die Verkündigung des Reiches Gottes, die Verklärung auf dem Berg Tabor, die Einsetzung der Eucharistie.\n• Schmerzhaft (Dienstag und Freitag): das Gebet am Ölberg, die Geißelung, die Dornenkrönung, der Kreuzweg, die Kreuzigung.\n• Glorreich (Mittwoch und Sonntag): die Auferstehung, die Himmelfahrt, die Herabkunft des Heiligen Geistes, die Aufnahme Mariens in den Himmel, die Krönung Mariens." },
      { icon: "❤️", name: "Der Barmherzigkeitsrosenkranz", text: "Was ist das für ein Gebet?\nDen Barmherzigkeitsrosenkranz diktierte der Herr Jesus selbst der heiligen Faustyna Kowalska 1935 in Vilnius; seine Worte sind in ihrem „Tagebuch“ festgehalten. In der ganzen Welt verbreiteten ihn die Apostel der Barmherzigkeit Gottes, besonders der heilige Johannes Paul II., der Schwester Faustyna im Jahr 2000 heiligsprach und den Barmherzigkeitssonntag einführte (der erste Sonntag nach Ostern). Man betet ihn an einem gewöhnlichen Rosenkranz; er dauert nur wenige Minuten.\n\nWann betet man ihn?\nBesonders um 15 Uhr — in der Stunde der Barmherzigkeit, der Todesstunde Jesu am Kreuz. Jesus versprach große Gnaden denen, die ihn beten, besonders an der Seite von Sterbenden. Vom Karfreitag bis zum Barmherzigkeitssonntag wird eine Novene aus diesem Gebet gehalten.\n\nWie betet man an den Perlen?\n[Zu Beginn] Kreuzzeichen, dann: „Vater unser“, „Gegrüßet seist du, Maria“ und das Glaubensbekenntnis.\n[An den großen Perlen — vor jedem Gesätz] „Ewiger Vater, ich opfere dir auf den Leib und das Blut, die Seele und die Gottheit deines über alles geliebten Sohnes, unseres Herrn Jesus Christus, zur Sühne für unsere Sünden und die Sünden der ganzen Welt.“\n[An den kleinen Perlen — 10-mal] „Durch sein schmerzhaftes Leiden habe Erbarmen mit uns und mit der ganzen Welt.“\nEbenso betet man alle fünf Gesätze.\n[Zum Abschluss — 3-mal] „Heiliger Gott, heiliger starker Gott, heiliger unsterblicher Gott, hab Erbarmen mit uns und mit der ganzen Welt.“\n[Man kann hinzufügen] „O Blut und Wasser, aus dem Herzen Jesu als Quelle der Barmherzigkeit für uns hervorgeströmt — ich vertraue auf dich.“" },
      { icon: "💙", name: "Unter deinen Schutz und Schirm", text: "Unter deinen Schutz und Schirm fliehen wir,\no heilige Gottesgebärerin.\nVerschmähe nicht unser Gebet in unseren Nöten,\nsondern erlöse uns jederzeit von allen Gefahren,\no du glorwürdige und gebenedeite Jungfrau.\nUnsere Frau, unsere Mittlerin, unsere Fürsprecherin,\nversöhne uns mit deinem Sohne,\nempfiehl uns deinem Sohne,\nstelle uns vor deinem Sohne.\nAmen." },
    ],
    songs: [
      { title: "Großer Gott, wir loben dich", meta: "Kirchenlied · I. Franz, 1771", lyrics: "Großer Gott, wir loben dich,\nHerr, wir preisen deine Stärke.\nVor dir neigt die Erde sich\nund bewundert deine Werke.\nWie du warst vor aller Zeit,\nso bleibst du in Ewigkeit." },
      { title: "Lobe den Herren", meta: "Kirchenlied · J. Neander, 1680", lyrics: "Lobe den Herren, den mächtigen König der Ehren,\nmeine geliebete Seele, das ist mein Begehren.\nKommet zuhauf, Psalter und Harfe, wacht auf,\nlasset den Lobgesang hören!" },
      { title: "Nun danket alle Gott", meta: "Kirchenlied · M. Rinckart, 1636", lyrics: "Nun danket alle Gott\nmit Herzen, Mund und Händen,\nder große Dinge tut\nan uns und allen Enden;\nder uns von Mutterleib\nund Kindesbeinen an\nunzählig viel zugut\nbis hierher hat getan." },
    ],
    knowledge: [
      { tab: "Kirchenjahr", intro: "Die Kirche erlebt jedes Jahr als einen Weg durch das Leben Christi — von der Erwartung über Geburt und Leiden bis zur Auferstehung.", cards: [
        { icon: "🕯", title: "Advent", text: "Vier Wochen freudiger Erwartung der Ankunft des Erlösers. Die Zeit des Adventskranzes und der Roratemessen." },
        { icon: "⭐", title: "Weihnachten", text: "Das Fest der Geburt Jesu in Betlehem. Die Weihnachtszeit dauert bis zum Fest der Taufe des Herrn; ihr Herz ist die Christmette." },
        { icon: "✝", title: "Fastenzeit", text: "Vierzig Tage der Umkehr, des Gebets, des Fastens und des Almosengebens — vom Aschermittwoch bis Gründonnerstag." },
        { icon: "🌅", title: "Ostern", text: "Die Auferstehung des Herrn — das höchste Fest der Christen. Die österliche Freude dauert fünfzig Tage, bis Pfingsten." },
        { icon: "🌿", title: "Zeit im Jahreskreis", text: "Eine Zeit des Wachsens im Glauben, Tag für Tag. Die grüne Farbe symbolisiert Hoffnung und Leben." },
      ]},
      { tab: "Sakramente", intro: "Die sieben Sakramente sind sichtbare Zeichen unsichtbarer Gnade, die den Menschen von der Geburt bis zum Ende des irdischen Weges begleiten.", cards: [
        { icon: "💧", title: "Taufe", text: "Das Tor zum Leben im Geist — Abwaschung der Erbsünde und Eingliederung in die Gemeinschaft der Kirche." },
        { icon: "🔥", title: "Firmung", text: "Stärkung mit den Gaben des Heiligen Geistes zu einem reifen und mutigen Glaubenszeugnis." },
        { icon: "🍞", title: "Eucharistie", text: "Quelle und Höhepunkt des christlichen Lebens — die reale Gegenwart Christi in den Gestalten von Brot und Wein." },
        { icon: "🕊", title: "Buße", text: "Das Sakrament der Barmherzigkeit — Versöhnung mit Gott und der Kirche durch das Bekenntnis der Sünden." },
        { icon: "🙌", title: "Krankensalbung", text: "Stärkung und Trost für Leidende und Kranke — ein Zeichen der Nähe Gottes in der Schwachheit." },
        { icon: "💍", title: "Ehe", text: "Der Bund von Mann und Frau — ein Bild der Liebe Christi zur Kirche." },
        { icon: "⛪", title: "Weihesakrament", text: "Das Sakrament des Dienstes — die Sendung, das Volk Gottes zu lehren, zu heiligen und zu leiten." },
      ]},
      { tab: "Engel", intro: "„Denn er befiehlt seinen Engeln, dich zu behüten auf all deinen Wegen“ (Psalm 91,11).", cards: [
        { icon: "👑", title: "Seraphim und Cherubim", text: "Dem Thron Gottes am nächsten. Die Seraphim brennen vor Liebe („Heilig, heilig, heilig“ — Jes 6); die Cherubim hüten Gottes Herrlichkeit." },
        { icon: "🛡", title: "Michael — „Wer ist wie Gott?“", text: "Anführer der himmlischen Heerscharen, Bezwinger des Bösen, Patron der Soldaten und Beschützer der Kirche." },
        { icon: "📯", title: "Gabriel — der Bote", text: "Er verkündete Maria die Geburt Jesu. Sein Name bedeutet „Gott ist meine Stärke“. Patron der Boten und Diplomaten." },
        { icon: "🌿", title: "Raphael — der Heiler", text: "„Gott heilt“ — Begleiter des Tobias auf seiner Reise, Patron der Reisenden, Kranken und Ärzte." },
        { icon: "👼", title: "Schutzengel", text: "Nach der Überlieferung hat jeder Mensch einen Engel, der ihn beschützt und führt. Ihr Fest wird am 2. Oktober gefeiert." },
      ]},
    ],
    facts: [
      { icon: "📖", title: "Bestseller aller Zeiten", text: "Die Bibel ist das meistverlegte Buch der Welt — ganz oder teilweise in mehr als 3600 Sprachen übersetzt." },
      { icon: "🐟", title: "Das geheime Zeichen des Fisches", text: "Das griechische Wort ICHTHYS (Fisch) ist ein Akrostichon: „Jesus Christus, Gottes Sohn, Erlöser“. Der Fisch war ein Geheimzeichen der ersten Christen." },
      { icon: "🙏", title: "Amen — so sei es", text: "Das Wort „Amen“ stammt aus dem Hebräischen und bedeutet „wahrlich, so sei es“. Es klingt in Hunderten von Sprachen fast gleich." },
      { icon: "🕯", title: "Die Katakomben Roms", text: "Die unterirdischen Gänge, in denen die ersten Christen beteten und ihre Toten bestatteten, erstrecken sich über 150 Kilometer unter Rom." },
      { icon: "😭", title: "Der kürzeste Vers", text: "Der kürzeste Vers der Bibel lautet „Jesus weinte“ (Joh 11,35) — zwei Worte, die zeigen, wie nah Gott dem menschlichen Schmerz ist." },
      { icon: "🎄", title: "Woher kommt der Weihnachtsbaum?", text: "Der Brauch, einen Baum zu schmücken, entstand im 16. Jahrhundert in deutschen Landen — der immergrüne Baum symbolisiert das ewige Leben." },
      { icon: "⛪", title: "Die älteste Hymne", text: "„Phos Hilaron“ (Heiteres Licht) wird seit dem 3. Jahrhundert ununterbrochen gesungen — die älteste bis heute gebrauchte christliche Hymne." },
      { icon: "🔔", title: "Der Angelus dreimal täglich", text: "Die Kirchenglocken läuten traditionell um 6, 12 und 18 Uhr zum Angelusgebet — ein Brauch aus dem 13. Jahrhundert." },
    ],
  },

  /* ==================== FRANÇAIS ==================== */
  fr: {
    ui: {
      nav_home: "Accueil", nav_prayers: "Prières", nav_songs: "Chants",
      nav_knowledge: "Foi", nav_facts: "Le saviez-vous ?", nav_candles: "Chapelle",
      hero_kicker: "Un compagnon pour le chrétien",
      hero_title: "Toujours fidèles — dans la prière, le chant et la vie quotidienne",
      hero_sub: "Un lieu de silence et de lumière. Un recueil de prières, de chants et de connaissances sur la foi — en cinq langues, pour tous ceux qui cherchent Dieu.",
      hero_cta1: "Ouvrir le livre de prières", hero_cta2: "Allumer un cierge 🕯",
      verse_label: "Verset du jour",
      prayers_title: "Prières",
      prayers_sub: "Des paroles qui, depuis des siècles, élèvent les hommes vers le ciel. Cliquez pour ouvrir une prière.",
      songs_title: "Chants",
      songs_sub: "Celui qui chante prie deux fois — saint Augustin.",
      knowledge_title: "Connaître la foi",
      knowledge_sub: "L'année liturgique, les sacrements et les anges — découvrez la richesse de la tradition chrétienne.",
      facts_title: "Le saviez-vous ?",
      facts_sub: "Des faits étonnants tirés de deux mille ans d'histoire chrétienne.",
      candles_title: "Chapelle de lumière",
      candles_sub: "Allumez un cierge virtuel à votre intention. Que sa flamme vous rappelle votre prière.",
      candles_placeholder: "Votre intention (ex. pour ma famille)...",
      candles_btn: "Allumer un cierge",
      candles_note: "Les cierges restent allumés sur cet appareil pendant 7 jours.",
      candles_empty: "Soyez la première personne à allumer un cierge aujourd'hui...",
      tts_listen: "Écouter",
      tts_stop: "Arrêter",
      ed_mode: "Mode édition",
      ed_edit: "Modifier",
      ed_add_prayer: "Ajouter une prière",
      ed_add_song: "Ajouter un chant",
      ed_add_fact: "Ajouter une anecdote",
      ed_add_card: "Ajouter une carte",
      ed_icon: "Icône (émoji)",
      ed_name: "Titre",
      ed_text: "Texte",
      ed_meta: "Légende (ex. auteur, année)",
      ed_lyrics: "Paroles",
      ed_save: "Enregistrer",
      ed_cancel: "Annuler",
      ed_delete: "Supprimer",
      ed_revert: "Restaurer l'original",
      ed_export: "Exporter",
      ed_import: "Importer",
      ed_done: "Terminer l'édition",
      ed_hint: "Cliquez sur un drapeau pour ajouter une traduction dans une autre langue. À défaut de traduction, une autre version linguistique disponible est affichée.",
      ed_need_content: "Remplissez le contenu dans au moins une langue.",
      ed_import_ok: "Vos contenus ont été importés.",
      ed_import_err: "Impossible de lire le fichier.",
      ed_export_ok: "Un fichier avec vos contenus a été téléchargé.",
      ed_confirm_delete: "Supprimer cet élément ?",
      footer_verse: "« Je suis la lumière du monde. Celui qui me suit ne marchera pas dans les ténèbres. » — Jn 8,12",
      footer_note: "Créé avec foi et espérance · Soli Deo Gloria",
    },
    verses: [
      { t: "Le Seigneur est mon berger : je ne manque de rien.", r: "Psaume 23,1" },
      { t: "Je puis tout en Celui qui me fortifie.", r: "Ph 4,13" },
      { t: "Ne crains pas, car je suis avec toi.", r: "Is 41,10" },
      { t: "L'amour prend patience ; l'amour rend service.", r: "1 Co 13,4" },
      { t: "Venez à moi, vous tous qui peinez sous le poids du fardeau, et moi, je vous procurerai le repos.", r: "Mt 11,28" },
      { t: "Soyez forts dans le Seigneur et dans la vigueur de sa force.", r: "Ep 6,10" },
      { t: "Crée en moi un cœur pur, ô mon Dieu.", r: "Psaume 51,12" },
    ],
    prayers: [
      { icon: "✝", name: "Notre Père", text: "Notre Père, qui es aux cieux,\nque ton nom soit sanctifié,\nque ton règne vienne,\nque ta volonté soit faite sur la terre comme au ciel.\nDonne-nous aujourd'hui notre pain de ce jour.\nPardonne-nous nos offenses,\ncomme nous pardonnons aussi à ceux qui nous ont offensés.\nEt ne nous laisse pas entrer en tentation,\nmais délivre-nous du Mal.\nAmen." },
      { icon: "🌹", name: "Je vous salue, Marie", text: "Je vous salue, Marie, pleine de grâce ;\nle Seigneur est avec vous.\nVous êtes bénie entre toutes les femmes,\net Jésus, le fruit de vos entrailles, est béni.\nSainte Marie, Mère de Dieu,\npriez pour nous, pauvres pécheurs,\nmaintenant et à l'heure de notre mort.\nAmen." },
      { icon: "✨", name: "Gloire au Père", text: "Gloire au Père, et au Fils, et au Saint-Esprit,\ncomme il était au commencement,\nmaintenant et toujours,\net dans les siècles des siècles.\nAmen." },
      { icon: "👼", name: "Ange de Dieu", text: "Ange de Dieu, qui es mon gardien,\net à qui la bonté divine m'a confié,\néclaire-moi, garde-moi,\nconduis-moi et dirige-moi.\nAmen." },
      { icon: "🛡", name: "Prière à saint Michel", text: "Saint Michel Archange, défendez-nous dans le combat ;\nsoyez notre secours contre la malice et les embûches du démon.\nQue Dieu exerce sur lui son empire, nous vous en supplions ;\net vous, Prince de la milice céleste,\npar le pouvoir divin, refoulez en enfer Satan\net les autres esprits mauvais qui rôdent dans le monde pour la perte des âmes.\nAmen." },
      { icon: "📜", name: "Je crois en Dieu (Symbole des Apôtres)", text: "Je crois en Dieu, le Père tout-puissant, créateur du ciel et de la terre.\nEt en Jésus-Christ, son Fils unique, notre Seigneur,\nqui a été conçu du Saint-Esprit, est né de la Vierge Marie,\na souffert sous Ponce Pilate, a été crucifié, est mort et a été enseveli,\nest descendu aux enfers, le troisième jour est ressuscité des morts,\nest monté aux cieux, est assis à la droite de Dieu le Père tout-puissant,\nd'où il viendra juger les vivants et les morts.\nJe crois en l'Esprit Saint, à la sainte Église catholique,\nà la communion des saints, à la rémission des péchés,\nà la résurrection de la chair, à la vie éternelle.\nAmen." },
      { icon: "📿", name: "Le Rosaire (chapelet)", text: "Qu'est-ce que cette prière ?\nLe Rosaire est une prière méditative : en répétant le « Je vous salue, Marie », nous contemplons avec Marie les événements les plus importants de la vie de Jésus, appelés mystères. Selon la tradition, la Vierge Marie elle-même l'a confié à saint Dominique (XIIIᵉ siècle) ; il fut répandu par les dominicains, notamment le bienheureux Alain de la Roche. Le pape Léon XIII — « le pape du Rosaire » — en fut un grand promoteur, et les mystères lumineux ont été ajoutés par saint Jean-Paul II en 2002.\n\nQuand le prier ?\nÀ tout moment — le plus souvent le soir, en famille ou seul. Octobre est le mois du Rosaire (la fête de Notre-Dame du Rosaire est célébrée le 7 octobre), et chaque groupe de mystères a ses jours traditionnels de la semaine.\n\nComment prier sur les grains ?\n[Sur la croix] Le signe de la croix, puis le « Je crois en Dieu » (Symbole des Apôtres).\n[Sur le premier gros grain] « Notre Père ».\n[Sur les trois petits grains] Trois « Je vous salue, Marie » — pour la foi, l'espérance et la charité.\n[Avant la médaille] « Gloire au Père ».\n[Annonce du mystère] Nomme le mystère à méditer, par exemple : « Premier mystère joyeux — l'Annonciation ».\n[Sur le gros grain] « Notre Père ».\n[Sur les dix petits grains] Dix « Je vous salue, Marie » en méditant le mystère.\n[Après chaque dizaine] « Gloire au Père » et la prière de Fatima : « Ô mon Jésus, pardonne-nous nos péchés, préserve-nous du feu de l'enfer, conduis au ciel toutes les âmes, spécialement celles qui ont le plus besoin de ta miséricorde. »\nLes quatre dizaines suivantes se prient de la même manière. [Pour conclure] « Salve Regina » (Salut, ô Reine) et le signe de la croix.\n\nLes mystères du Rosaire :\n• Joyeux (lundi et samedi) : l'Annonciation, la Visitation, la Nativité, la Présentation au Temple, le Recouvrement de Jésus au Temple.\n• Lumineux (jeudi) : le Baptême au Jourdain, les Noces de Cana, l'annonce du Royaume de Dieu, la Transfiguration, l'institution de l'Eucharistie.\n• Douloureux (mardi et vendredi) : l'Agonie à Gethsémani, la Flagellation, le Couronnement d'épines, le Portement de croix, la Crucifixion.\n• Glorieux (mercredi et dimanche) : la Résurrection, l'Ascension, la Pentecôte, l'Assomption de Marie, le Couronnement de Marie au ciel." },
      { icon: "❤️", name: "Le Chapelet de la Miséricorde Divine", text: "Qu'est-ce que cette prière ?\nLe Chapelet de la Miséricorde Divine a été dicté par le Seigneur Jésus lui-même à sainte Faustine Kowalska à Vilnius en 1935 ; ses paroles sont consignées dans son « Petit Journal ». Il a été répandu dans le monde entier par les apôtres de la Miséricorde Divine, en particulier saint Jean-Paul II, qui a canonisé sœur Faustine en 2000 et institué le dimanche de la Miséricorde Divine (le premier dimanche après Pâques). Il se prie sur un chapelet ordinaire et ne dure que quelques minutes.\n\nQuand le prier ?\nSurtout à 15 heures — à l'Heure de la Miséricorde, l'heure de la mort de Jésus sur la croix. Jésus a promis de grandes grâces à ceux qui le prient, particulièrement auprès des mourants. Du Vendredi saint au dimanche de la Miséricorde, on prie une neuvaine de chapelets.\n\nComment prier sur les grains ?\n[Au début] Le signe de la croix, puis : « Notre Père », « Je vous salue, Marie » et le « Je crois en Dieu ».\n[Sur les gros grains — avant chaque dizaine] « Père Éternel, je T'offre le Corps et le Sang, l'Âme et la Divinité de Ton Fils bien-aimé, notre Seigneur Jésus-Christ, en réparation de nos péchés et de ceux du monde entier. »\n[Sur les petits grains — 10 fois] « Par Sa douloureuse Passion, sois miséricordieux pour nous et pour le monde entier. »\nLes cinq dizaines se prient de la même manière.\n[Pour conclure — 3 fois] « Dieu Saint, Dieu Fort, Dieu Immortel, prends pitié de nous et du monde entier. »\n[On peut ajouter] « Ô Sang et Eau, jaillis du Cœur de Jésus comme source de miséricorde pour nous — j'ai confiance en Toi. »" },
      { icon: "💙", name: "Sous ta protection", text: "Sous ta protection, nous nous réfugions,\nsainte Mère de Dieu ;\nne rejette pas les prières\nque nous t'adressons dans nos nécessités,\nmais délivre-nous toujours de tous les dangers,\nô Vierge glorieuse et bénie.\nAmen." },
    ],
    songs: [
      { title: "Il est né le divin Enfant", meta: "Noël traditionnel · XIXᵉ siècle", lyrics: "Il est né le divin Enfant,\njouez hautbois, résonnez musettes !\nIl est né le divin Enfant,\nchantons tous son avènement !\n\nDepuis plus de quatre mille ans,\nnous le promettaient les prophètes ;\ndepuis plus de quatre mille ans,\nnous attendions cet heureux temps." },
      { title: "Minuit, chrétiens", meta: "Cantique · P. Cappeau / A. Adam, 1847", lyrics: "Minuit, chrétiens, c'est l'heure solennelle\noù l'Homme-Dieu descendit jusqu'à nous,\npour effacer la tache originelle\net de son Père arrêter le courroux.\n\nPeuple à genoux, attends ta délivrance :\nNoël ! Noël ! Voici le Rédempteur !" },
      { title: "Peuple fidèle", meta: "Adeste fideles · XVIIIᵉ siècle", lyrics: "Peuple fidèle, le Seigneur t'appelle :\nc'est fête sur terre, le Christ est né.\nViens à la crèche voir le Roi du monde.\n\nEn lui viens reconnaître,\nen lui viens reconnaître,\nen lui viens reconnaître ton Dieu, ton Sauveur." },
    ],
    knowledge: [
      { tab: "Année liturgique", intro: "L'Église vit chaque année comme un pèlerinage à travers la vie du Christ — de l'attente, par la naissance et la passion, jusqu'à la résurrection.", cards: [
        { icon: "🕯", title: "Avent", text: "Quatre semaines d'attente joyeuse de la venue du Sauveur. Le temps de la couronne de l'Avent et des messes de l'aurore." },
        { icon: "⭐", title: "Noël", text: "La célébration de la naissance de Jésus à Bethléem. Le temps de Noël dure jusqu'au Baptême du Seigneur, avec la messe de minuit en son cœur." },
        { icon: "✝", title: "Carême", text: "Quarante jours de conversion, de prière, de jeûne et d'aumône — du mercredi des Cendres au Jeudi saint." },
        { icon: "🌅", title: "Pâques", text: "La Résurrection du Seigneur — la plus grande fête chrétienne. La joie pascale dure cinquante jours, jusqu'à la Pentecôte." },
        { icon: "🌿", title: "Temps ordinaire", text: "Un temps pour grandir dans la foi, jour après jour. Sa couleur verte symbolise l'espérance et la vie." },
      ]},
      { tab: "Sacrements", intro: "Les sept sacrements sont des signes visibles de la grâce invisible, accompagnant l'homme de sa naissance jusqu'au terme de son chemin terrestre.", cards: [
        { icon: "💧", title: "Baptême", text: "La porte de la vie dans l'Esprit — purification du péché originel et entrée dans la communauté de l'Église." },
        { icon: "🔥", title: "Confirmation", text: "L'affermissement par les dons de l'Esprit Saint pour un témoignage de foi mûr et courageux." },
        { icon: "🍞", title: "Eucharistie", text: "Source et sommet de la vie chrétienne — la présence réelle du Christ sous les espèces du pain et du vin." },
        { icon: "🕊", title: "Pénitence", text: "Le sacrement de la miséricorde — la réconciliation avec Dieu et l'Église par l'aveu des péchés." },
        { icon: "🙌", title: "Onction des malades", text: "Force et réconfort pour ceux qui souffrent — signe de la proximité de Dieu dans la faiblesse." },
        { icon: "💍", title: "Mariage", text: "L'alliance d'un homme et d'une femme — image de l'amour du Christ pour l'Église." },
        { icon: "⛪", title: "Ordre", text: "Le sacrement du service — la mission d'enseigner, de sanctifier et de conduire le peuple de Dieu." },
      ]},
      { tab: "Les anges", intro: "« Il donnera pour toi ordre à ses anges de te garder en toutes tes voies » (Psaume 91,11).", cards: [
        { icon: "👑", title: "Séraphins et chérubins", text: "Les plus proches du trône de Dieu. Les séraphins brûlent d'amour (« Saint, Saint, Saint » — Is 6) ; les chérubins gardent la gloire divine." },
        { icon: "🛡", title: "Michel — « Qui est comme Dieu ? »", text: "Chef des armées célestes, vainqueur du mal, patron des soldats et défenseur de l'Église." },
        { icon: "📯", title: "Gabriel — le messager", text: "Il annonça à Marie la naissance de Jésus. Son nom signifie « Dieu est ma force ». Patron des messagers et des diplomates." },
        { icon: "🌿", title: "Raphaël — le guérisseur", text: "« Dieu guérit » — compagnon de Tobie en voyage, patron des voyageurs, des malades et des médecins." },
        { icon: "👼", title: "L'ange gardien", text: "Selon la tradition, chaque personne a un ange qui la protège et la guide. Leur fête est célébrée le 2 octobre." },
      ]},
    ],
    facts: [
      { icon: "📖", title: "Best-seller de tous les temps", text: "La Bible est le livre le plus édité au monde — traduite, en tout ou en partie, en plus de 3 600 langues." },
      { icon: "🐟", title: "Le signe secret du poisson", text: "Le mot grec ICHTHYS (poisson) est un acrostiche : « Jésus-Christ, Fils de Dieu, Sauveur ». Le poisson était le signe secret des premiers chrétiens." },
      { icon: "🙏", title: "Amen — qu'il en soit ainsi", text: "Le mot « Amen » vient de l'hébreu et signifie « en vérité, qu'il en soit ainsi ». Il se prononce presque à l'identique dans des centaines de langues." },
      { icon: "🕯", title: "Les catacombes de Rome", text: "Les galeries souterraines où priaient les premiers chrétiens et où ils enterraient leurs morts s'étendent sur plus de 150 kilomètres sous Rome." },
      { icon: "😭", title: "Le verset le plus court", text: "Le verset le plus court de la Bible est « Jésus pleura » (Jn 11,35) — deux mots qui montrent combien Dieu est proche de la douleur humaine." },
      { icon: "🎄", title: "D'où vient le sapin de Noël ?", text: "La coutume de décorer un sapin est née dans les pays germaniques au XVIᵉ siècle — l'arbre toujours vert symbolise la vie éternelle." },
      { icon: "⛪", title: "La plus ancienne hymne", text: "« Phos Hilaron » (Joyeuse Lumière) est chantée sans interruption depuis le IIIᵉ siècle — la plus ancienne hymne chrétienne encore en usage." },
      { icon: "🔔", title: "L'Angélus trois fois par jour", text: "Les cloches des églises sonnent traditionnellement à 6 h, midi et 18 h pour appeler à la prière de l'Angélus — une coutume du XIIIᵉ siècle." },
    ],
  },
};
